"""empty message

Revision ID: bdf604285a84
Revises: 
Create Date: 2023-04-30 02:32:57.220081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf604285a84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subTitle', sa.String(), nullable=True),
    sa.Column('hardness', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('sourceUrl', sa.String(), nullable=False),
    sa.Column('imgAlt', sa.String(), nullable=True),
    sa.Column('imgUrl', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('publishedTime', sa.DateTime(), nullable=False),
    sa.Column('click', sa.Integer(), nullable=True),
    sa.Column('like', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.create_index(op.f('ix_article_subTitle'), 'article', ['subTitle'], unique=False)
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_index(op.f('ix_article_subTitle'), table_name='article')
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
